//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    
    
    public partial class ApolloPro {
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// Localize1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize1;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// LoadingIndicator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.LoadingIndicator LoadingIndicator1;
        
        /// <summary>
        /// Viewport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Viewport Viewport1;
        
        /// <summary>
        /// Banner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Banner;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Panel1;
        
        /// <summary>
        /// MainPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MainPanel;
        
        /// <summary>
        /// MapContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapContainer;
        
        /// <summary>
        /// MapToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapToolbar.MapToolbar MapToolbar;
        
        /// <summary>
        /// TabPabelSearchResult control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel TabPabelSearchResult;
        
        /// <summary>
        /// SearchResultPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.SearchResultPanel.SearchResultPanel SearchResultPanel1;
        
        /// <summary>
        /// Sidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Sidebar;
        
        /// <summary>
        /// MapCont control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapCont;
        
        /// <summary>
        /// MapContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.TabPanel MapContent;
        
        /// <summary>
        /// MapContentLayers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentLayers;
        
        /// <summary>
        /// MapContentServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentServices;
        
        /// <summary>
        /// MapContentCategorized control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentCategorized;
        
        /// <summary>
        /// SearchPanelInSidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel SearchPanelInSidebar;
        
        /// <summary>
        /// MetaSearchPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.Apollo.MetaSearchPanel.MetaSearchPanel MetaSearchPanel;
        
        /// <summary>
        /// CatalogPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel CatalogPanel;
        
        /// <summary>
        /// ApolloCatalogElement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.Apollo.ApolloCatalog.ApolloCatalog ApolloCatalogElement;
        
        /// <summary>
        /// ClipZipShipCont control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel ClipZipShipCont;
        
        /// <summary>
        /// ClipZipShipPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.Apollo.ClipZipShipPanel.ClipZipShipPanel ClipZipShipPanel;
        
        /// <summary>
        /// GeoprocessingPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel GeoprocessingPanel;
        
        /// <summary>
        /// GeoProcessPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.Apollo.GeoProcessingPanel.GeoProcessingPanel GeoProcessPanel;
        
        /// <summary>
        /// AnalysesPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Analyses.AnalysesControl AnalysesPanel;
        
        /// <summary>
        /// View3DPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.View3DPanel View3DPanel;
        
        /// <summary>
        /// ShadowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DynamicShadowControl ShadowControl;
        
        /// <summary>
        /// ObjectsAndFeaturesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ObjectsAndFeaturesControl ObjectsAndFeaturesControl;
        
        /// <summary>
        /// SettingsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.SettingsPanel SettingsPanel;
        
        /// <summary>
        /// GazetteerPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.WFSG.Search.GazetteerPanel GazetteerPanel;
        
        /// <summary>
        /// FeatureInfoControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.FeatureInfo.FeatureInfoControl FeatureInfoControl1;
        
        /// <summary>
        /// DataSourcesWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window DataSourcesWindow;
        
        /// <summary>
        /// MapServicesManagerControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapServices.MapServicesManagerControl MapServicesManagerControl1;
        
        /// <summary>
        /// NewDataSourceWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NewDataSourceWindow;
        
        /// <summary>
        /// AddNewMapServiceControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapServices.AddNewMapServiceControl AddNewMapServiceControl1;
        
        /// <summary>
        /// LegendWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window LegendWindow;
        
        /// <summary>
        /// LegendControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl LegendControl;
        
        /// <summary>
        /// CategoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window CategoryWindow;
        
        /// <summary>
        /// CategoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl CategoryControl;
        
        /// <summary>
        /// NotificationHistoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NotificationHistoryWindow;
        
        /// <summary>
        /// NotificationHistoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Notification.NotificationHistoryControl NotificationHistoryControl;
        
        /// <summary>
        /// ChooseLayersWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ChooseLayersWindow;
        
        /// <summary>
        /// TabPanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.TabPanel TabPanel2;
        
        /// <summary>
        /// Legend2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl Legend2Control;
        
        /// <summary>
        /// Category2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl Category2Control;
        
        /// <summary>
        /// PreviewMapWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.PreviewMapWindow PreviewMapWindow;
        
        /// <summary>
        /// UserMapsWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window UserMapsWindow;
        
        /// <summary>
        /// MapStorageControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapStorageControl MapStorageControl1;
        
        /// <summary>
        /// ScaleBandWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ScaleBandWindow;
        
        /// <summary>
        /// ScaleBandControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ScaleBandControl ScaleBandControl1;
        
        /// <summary>
        /// WebBrowser1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.WebBrowser WebBrowser1;
        
        /// <summary>
        /// DataWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Data.DataWindow DataWindow;
        
        /// <summary>
        /// InsertFeatureWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertFeatureWindow;
        
        /// <summary>
        /// InsertFeaturePanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.InsertFeaturePanel.InsertFeaturePanel InsertFeaturePanel1;
        
        /// <summary>
        /// WMCActionWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window WMCActionWindow;
        
        /// <summary>
        /// WMCActionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.WMC.Operations.WMCActionControl WMCActionControl;
        
        /// <summary>
        /// AboutWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AboutWindow;
        
        /// <summary>
        /// AboutControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.Controls.AboutControl AboutControl1;
        
        /// <summary>
        /// DynamicObjectViewWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window DynamicObjectViewWindow;
        
        /// <summary>
        /// DynamicObjectViewControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.DynamicObjectViewControl DynamicObjectViewControl1;
        
        /// <summary>
        /// InsertTextWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertTextWindow;
        
        /// <summary>
        /// InsertTextControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.InsertTextControl InsertTextControl;
        
        /// <summary>
        /// MetadataAdvancedWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window MetadataAdvancedWindow;
        
        /// <summary>
        /// MetaAdvancedSearchPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.CSW.Search.MetaAdvancedSearchPanel MetaAdvancedSearchPanel;
        
        /// <summary>
        /// ScaleBandEditWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ScaleBandEditWindow;
        
        /// <summary>
        /// ScaleBandEditControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ScaleBandEditControl ScaleBandEditControl;
        
        /// <summary>
        /// AuthenticationWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AuthenticationWindow;
        
        /// <summary>
        /// AuthenticationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Security.AuthenticationControl AuthenticationControl;
        
        /// <summary>
        /// StyleWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window StyleWindow;
        
        /// <summary>
        /// StyleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Style.StyleControl StyleControl;
        
        /// <summary>
        /// PrintingWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Printing.Controls.PrintingWindow PrintingWindow;
        
        /// <summary>
        /// InsertFeatureWindowAttributes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertFeatureWindowAttributes;
        
        /// <summary>
        /// RedliningWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window RedliningWindow;
        
        /// <summary>
        /// InsertFeatureControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.InsertFeatureControl InsertFeatureControl;
        
        /// <summary>
        /// ContinueGeometryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ContinueGeometryWindow;
        
        /// <summary>
        /// ContinueGeometryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.ContinueGeometryControl ContinueGeometryControl;
        
        /// <summary>
        /// SnapWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window SnapWindow;
        
        /// <summary>
        /// SnapControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.SnapControl SnapControl;
        
        /// <summary>
        /// QualityMonitorWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window QualityMonitorWindow;
        
        /// <summary>
        /// QualityMonitorControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.Geomedia.Web.SDI.QualityMonitor.Client.QualityMonitorControl QualityMonitorControl;
        
        /// <summary>
        /// QualityMonitorAdminWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window QualityMonitorAdminWindow;
        
        /// <summary>
        /// QualityMonitorAdminControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.Geomedia.Web.SDI.QualityMonitor.Client.Admin.QualityMonitorAdminControl QualityMonitorAdminControl;
        
        /// <summary>
        /// InsertMarkerAnnotationWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertMarkerAnnotationWindow;
        
        /// <summary>
        /// MarkerAnnotationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.MarkerAnnotationControl MarkerAnnotationControl;
        
        /// <summary>
        /// FeatureClassDefinition1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.PSS.FeatureClassDefinition FeatureClassDefinition1;
    }
}
