//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    
    
    public partial class Full {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// Banner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Banner;
        
        /// <summary>
        /// MapContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapContainer;
        
        /// <summary>
        /// MapToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapToolbar.MapToolbar MapToolbar;
        
        /// <summary>
        /// Sidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Sidebar;
        
        /// <summary>
        /// MapContentCont control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapContentCont;
        
        /// <summary>
        /// MapContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.TabPanel MapContent;
        
        /// <summary>
        /// MapContentLayers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentLayers;
        
        /// <summary>
        /// MapContentServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentServices;
        
        /// <summary>
        /// MapContentCategorized control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentCategorized;
        
        /// <summary>
        /// GazetteerPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.WFSG.Search.GazetteerPanel GazetteerPanel;
        
        /// <summary>
        /// SearchPanelInSidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel SearchPanelInSidebar;
        
        /// <summary>
        /// MetaSimpleSearchPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.CSW.Search.MetaSimpleSearchPanel MetaSimpleSearchPanel;
        
        /// <summary>
        /// MetaGridPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.CSW.Search.MetaGridPanel MetaGridPanel;
        
        /// <summary>
        /// AnalysesPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Analyses.AnalysesControl AnalysesPanel;
        
        /// <summary>
        /// View3DPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.View3DPanel View3DPanel;
        
        /// <summary>
        /// ShadowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DynamicShadowControl ShadowControl;
        
        /// <summary>
        /// ObjectsAndFeaturesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ObjectsAndFeaturesControl ObjectsAndFeaturesControl;
        
        /// <summary>
        /// SettingsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.SettingsPanel SettingsPanel;
        
        /// <summary>
        /// DataSourcesWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window DataSourcesWindow;
        
        /// <summary>
        /// NewDataSourceWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NewDataSourceWindow;
        
        /// <summary>
        /// AddNewMapServiceControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapServices.AddNewMapServiceControl AddNewMapServiceControl1;
        
        /// <summary>
        /// LegendWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window LegendWindow;
        
        /// <summary>
        /// LegendControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl LegendControl;
        
        /// <summary>
        /// CategoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window CategoryWindow;
        
        /// <summary>
        /// CategoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl CategoryControl;
        
        /// <summary>
        /// ChooseLayersWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ChooseLayersWindow;
        
        /// <summary>
        /// Legend2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl Legend2Control;
        
        /// <summary>
        /// Category2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl Category2Control;
        
        /// <summary>
        /// PreviewMapWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.PreviewMapWindow PreviewMapWindow;
        
        /// <summary>
        /// UserMapsWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window UserMapsWindow;
        
        /// <summary>
        /// NotificationHistoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NotificationHistoryWindow;
        
        /// <summary>
        /// ScaleBandWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ScaleBandWindow;
        
        /// <summary>
        /// WebBrowser1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.WebBrowser WebBrowser1;
        
        /// <summary>
        /// DataWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Data.DataWindow DataWindow;
        
        /// <summary>
        /// InsertFeatureWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertFeatureWindow;
        
        /// <summary>
        /// WMCActionWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window WMCActionWindow;
        
        /// <summary>
        /// WMCActionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.WMC.Operations.WMCActionControl WMCActionControl;
        
        /// <summary>
        /// AboutWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AboutWindow;
        
        /// <summary>
        /// DynamicObjectViewWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window DynamicObjectViewWindow;
        
        /// <summary>
        /// MetadataAdvancedWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window MetadataAdvancedWindow;
        
        /// <summary>
        /// MetaAdvancedSearchPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.CSW.Search.MetaAdvancedSearchPanel MetaAdvancedSearchPanel;
        
        /// <summary>
        /// ScaleBandEditWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ScaleBandEditWindow;
        
        /// <summary>
        /// ScaleBandEditControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ScaleBandEditControl ScaleBandEditControl;
        
        /// <summary>
        /// AuthenticationWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AuthenticationWindow;
        
        /// <summary>
        /// AuthenticationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Security.AuthenticationControl AuthenticationControl;
        
        /// <summary>
        /// StyleWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window StyleWindow;
        
        /// <summary>
        /// StyleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Style.StyleControl StyleControl;
        
        /// <summary>
        /// PrintingWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Printing.Controls.PrintingWindow PrintingWindow;
        
        /// <summary>
        /// InsertFeatureWindowAttributes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertFeatureWindowAttributes;
        
        /// <summary>
        /// RedliningWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window RedliningWindow;
        
        /// <summary>
        /// InsertFeatureControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.InsertFeatureControl InsertFeatureControl;
        
        /// <summary>
        /// ContinueGeometryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ContinueGeometryWindow;
        
        /// <summary>
        /// ContinueGeometryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.ContinueGeometryControl ContinueGeometryControl;
        
        /// <summary>
        /// InsertTextWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertTextWindow;
        
        /// <summary>
        /// InsertTextControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.InsertTextControl InsertTextControl;
        
        /// <summary>
        /// SnapWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window SnapWindow;
        
        /// <summary>
        /// SnapControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Edit.SnapControl SnapControl;
        
        /// <summary>
        /// QualityMonitorWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window QualityMonitorWindow;
        
        /// <summary>
        /// QualityMonitorControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.Geomedia.Web.SDI.QualityMonitor.Client.QualityMonitorControl QualityMonitorControl;
        
        /// <summary>
        /// QualityMonitorAdminWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window QualityMonitorAdminWindow;
        
        /// <summary>
        /// QualityMonitorAdminControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.Geomedia.Web.SDI.QualityMonitor.Client.Admin.QualityMonitorAdminControl QualityMonitorAdminControl;
        
        /// <summary>
        /// InsertMarkerAnnotationWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window InsertMarkerAnnotationWindow;
        
        /// <summary>
        /// MarkerAnnotationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.MarkerAnnotationControl MarkerAnnotationControl;
    }
}
