//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    
    
    public partial class GeomediaWebMapPublisherApplication {
        
        /// <summary>
        /// Html1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Html1;
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// Localize1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Localize Localize1;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// LoadingIndicator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.LoadingIndicator LoadingIndicator1;
        
        /// <summary>
        /// ViewPort1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Viewport ViewPort1;
        
        /// <summary>
        /// Banner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Banner;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Panel1;
        
        /// <summary>
        /// Panel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Panel2;
        
        /// <summary>
        /// MapContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapContainer;
        
        /// <summary>
        /// MapToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapToolbar.MapToolbar MapToolbar;
        
        /// <summary>
        /// DataPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Data.DataPanel DataPanel;
        
        /// <summary>
        /// Sidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Sidebar;
        
        /// <summary>
        /// InnerSidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel InnerSidebar;
        
        /// <summary>
        /// Panel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Panel3;
        
        /// <summary>
        /// MapContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.TabPanel MapContent;
        
        /// <summary>
        /// MapContentLayers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentLayers;
        
        /// <summary>
        /// MapContentServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentServices;
        
        /// <summary>
        /// MapContentCategorized control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentCategorized;
        
        /// <summary>
        /// View3DPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.View3DPanel View3DPanel;
        
        /// <summary>
        /// ShadowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DynamicShadowControl ShadowControl;
        
        /// <summary>
        /// ObjectsAndFeaturesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ObjectsAndFeaturesControl ObjectsAndFeaturesControl;
        
        /// <summary>
        /// SettingsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.SettingsPanel SettingsPanel;
        
        /// <summary>
        /// Panel6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Panel6;
        
        /// <summary>
        /// PreviewMapPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.PreviewMapPanel PreviewMapPanel;
        
        /// <summary>
        /// SimpleQueryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window SimpleQueryWindow;
        
        /// <summary>
        /// SimpleQueryPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.SimpleQueryControl SimpleQueryPanel;
        
        /// <summary>
        /// StyleWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window StyleWindow;
        
        /// <summary>
        /// StyleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Style.StyleControl StyleControl;
        
        /// <summary>
        /// DataSourcesWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window DataSourcesWindow;
        
        /// <summary>
        /// MapServicesManagerControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapServices.MapServicesManagerControl MapServicesManagerControl1;
        
        /// <summary>
        /// NewDataSourceWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NewDataSourceWindow;
        
        /// <summary>
        /// AddNewMapServiceControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapServices.AddNewMapServiceControl AddNewMapServiceControl1;
        
        /// <summary>
        /// LegendWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window LegendWindow;
        
        /// <summary>
        /// LegendControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl LegendControl;
        
        /// <summary>
        /// CategoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window CategoryWindow;
        
        /// <summary>
        /// CategoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl CategoryControl;
        
        /// <summary>
        /// ChooseLayersWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ChooseLayersWindow;
        
        /// <summary>
        /// TabPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.TabPanel TabPanel1;
        
        /// <summary>
        /// Legend2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl Legend2Control;
        
        /// <summary>
        /// Category2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl Category2Control;
        
        /// <summary>
        /// WebBrowser1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.WebBrowser WebBrowser1;
        
        /// <summary>
        /// AboutWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AboutWindow;
        
        /// <summary>
        /// AboutControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.SDIPortal.Controls.AboutControl AboutControl;
        
        /// <summary>
        /// AuthenticationWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AuthenticationWindow;
        
        /// <summary>
        /// AuthenticationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Security.AuthenticationControl AuthenticationControl;
        
        /// <summary>
        /// NotificationHistoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NotificationHistoryWindow;
        
        /// <summary>
        /// NotificationHistoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Notification.NotificationHistoryControl NotificationHistoryControl;
        
        /// <summary>
        /// UserMapsWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window UserMapsWindow;
        
        /// <summary>
        /// MapStorageControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapStorageControl MapStorageControl1;
        
        /// <summary>
        /// PrintingWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Printing.Controls.PrintingWindow PrintingWindow;
        
        /// <summary>
        /// FeatureInfoControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.FeatureInfo.FeatureInfoControl FeatureInfoControl1;
        
        /// <summary>
        /// FeatureClassDefinition1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.PSS.FeatureClassDefinition FeatureClassDefinition1;
    }
}
