//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    
    
    public partial class IWS {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ViewPort1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Viewport ViewPort1;
        
        /// <summary>
        /// Banner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Banner;
        
        /// <summary>
        /// Panel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Panel1;
        
        /// <summary>
        /// MapContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapContainer;
        
        /// <summary>
        /// MapToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapToolbar.MapToolbar MapToolbar;
        
        /// <summary>
        /// Sidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel Sidebar;
        
        /// <summary>
        /// MapContentCont control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Panel MapContentCont;
        
        /// <summary>
        /// MapContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.TabPanel MapContent;
        
        /// <summary>
        /// MapContentLayers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentLayers;
        
        /// <summary>
        /// MapContentServices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentServices;
        
        /// <summary>
        /// MapContentCategorized control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Map.MapLegendControl MapContentCategorized;
        
        /// <summary>
        /// View3DPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.View3DPanel View3DPanel;
        
        /// <summary>
        /// ShadowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DynamicShadowControl ShadowControl;
        
        /// <summary>
        /// ObjectsAndFeaturesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ObjectsAndFeaturesControl ObjectsAndFeaturesControl;
        
        /// <summary>
        /// SettingsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.SettingsPanel SettingsPanel;
        
        /// <summary>
        /// LanguageSelector1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.LanguageSelector.LanguageSelector LanguageSelector1;
        
        /// <summary>
        /// DataSourcesWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window DataSourcesWindow;
        
        /// <summary>
        /// NewDataSourceWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NewDataSourceWindow;
        
        /// <summary>
        /// AddNewMapServiceControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.MapServices.AddNewMapServiceControl AddNewMapServiceControl1;
        
        /// <summary>
        /// LegendWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window LegendWindow;
        
        /// <summary>
        /// LegendControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl LegendControl;
        
        /// <summary>
        /// CategoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window CategoryWindow;
        
        /// <summary>
        /// CategoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl CategoryControl;
        
        /// <summary>
        /// ChooseLayersWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ChooseLayersWindow;
        
        /// <summary>
        /// Legend2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.LegendControl Legend2Control;
        
        /// <summary>
        /// Category2Control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.DisplayCenter.CategoryControl Category2Control;
        
        /// <summary>
        /// NotificationHistoryWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window NotificationHistoryWindow;
        
        /// <summary>
        /// NotificationHistoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Notification.NotificationHistoryControl NotificationHistoryControl;
        
        /// <summary>
        /// PreviewMapWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.PreviewMapWindow PreviewMapWindow;
        
        /// <summary>
        /// UserMapsWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window UserMapsWindow;
        
        /// <summary>
        /// ScaleBandWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ScaleBandWindow;
        
        /// <summary>
        /// WebBrowser1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Layout.WebBrowser WebBrowser1;
        
        /// <summary>
        /// AboutWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AboutWindow;
        
        /// <summary>
        /// ScaleBandEditWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window ScaleBandEditWindow;
        
        /// <summary>
        /// ScaleBandEditControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.ScaleBandEditControl ScaleBandEditControl;
        
        /// <summary>
        /// AuthenticationWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window AuthenticationWindow;
        
        /// <summary>
        /// AuthenticationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Security.AuthenticationControl AuthenticationControl;
        
        /// <summary>
        /// StyleWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ExtJS.Controls.Window StyleWindow;
        
        /// <summary>
        /// StyleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Intergraph.WebSolutions.Core.WebClient.Controls.Style.StyleControl StyleControl;
    }
}
